import { KeyValObject } from "./types";

export const AVAIABLE_CURRENCIES: KeyValObject = {
  AED: "Dírham de los Emiratos Árabes Unidos",
  AFN: "Afgani",
  ALL: "Lek",
  AMD: "Dram armenio",
  ANG: "Florín antillano neerlandés",
  AOA: "Kwanza",
  ARS: "Peso argentino",
  AUD: "Dólar australiano",
  AWG: "Florín arubeño",
  AZN: "Manat azerbaiyano",
  BAM: "Marco convertible",
  BBD: "Dólar barbadense",
  BDT: "Taka",
  BGN: "Lev búlgaro",
  BHD: "Dinar bareiní",
  BIF: "Franco de Burundi",
  BMD: "Dólar bermudeño",
  BND: "Dólar de Brunéi",
  BOB: "Boliviano",
  BOV: "MVDOL",
  BRL: "Real brasileño",
  BSD: "Dólar bahameño",
  BTN: "Ngultrum",
  BWP: "Pula",
  BYN: "Rublo bielorruso",
  BZD: "Dólar beliceño",
  CAD: "Dólar canadiense",
  CDF: "Franco congoleño",
  CHF: "Franco suizo",
  CLF: "Unidad de fomento",
  CLP: "Peso chileno",
  CNY: "Yuan chino",
  COP: "Peso colombiano",
  CRC: "Colón costarricense",
  CUC: "Peso convertible",
  CUP: "Peso cubano",
  CVE: "Escudo caboverdiano",
  CZK: "Corona checa",
  DJF: "Franco yibutiano",
  DKK: "Corona danesa",
  DOP: "Peso dominicano",
  DZD: "Dinar argelino",
  EGP: "Libra egipcia",
  ERN: "Nakfa",
  ETB: "Birr etíope",
  EUR: "Euro",
  FJD: "Dólar fiyiano",
  FKP: "Libra malvinense",
  GBP: "Libra esterlina",
  GEL: "Lari",
  GHS: "Cedi ghanés",
  GIP: "Libra de Gibraltar",
  GMD: "Dalasi",
  GNF: "Franco guineano",
  GTQ: "Quetzal",
  GYD: "Dólar guyanés",
  HKD: "Dólar de Hong Kong",
  HNL: "Lempira",
  HRK: "Kuna",
  HTG: "Gourde",
  HUF: "Forinto",
  IDR: "Rupia indonesia",
  ILS: "Nuevo séquel israelí",
  INR: "Rupia india",
  IQD: "Dinar iraquí",
  IRR: "Rial iraní",
  ISK: "Corona islandesa",
  JMD: "Dólar jamaiquino",
  JOD: "Dinar jordano",
  JPY: "Yen",
  KES: "Chelín keniano",
  KGS: "Som",
  KHR: "Riel",
  KMF: "Franco comorense",
  KPW: "Won norcoreano",
  KRW: "Won",
  KWD: "Dinar kuwaití",
  KYD: "Dólar de las Islas Caimán",
  KZT: "Tenge",
  LAK: "Kip",
  LBP: "Libra libanesa",
  LKR: "Rupia de Sri Lanka",
  LRD: "Dólar liberiano",
  LSL: "Loti",
  LYD: "Dinar libio",
  MAD: "Dírham marroquí",
  MDL: "Leu moldavo",
  MGA: "Ariary malgache",
  MKD: "Denar",
  MMK: "Kyat",
  MNT: "Tugrik",
  MOP: "Pataca",
  MRU: "Uguiya",
  MUR: "Rupia de Mauricio",
  MVR: "Rufiyaa",
  MWK: "Kwacha",
  MXN: "Peso mexicano",
  MXV: "Unidad de Inversión (UDI) mexicana",
  MYR: "Ringgit malayo",
  MZN: "Metical mozambiqueño",
  NAD: "Dólar namibio",
  NGN: "Naira",
  NIO: "Córdoba",
  NOK: "Corona noruega",
  NPR: "Rupia nepalí",
  NZD: "Dólar neozelandés",
  OMR: "Rial omaní",
  PAB: "Balboa",
  PEN: "Sol",
  PGK: "Kina",
  PHP: "Peso filipino",
  PKR: "Rupia pakistaní",
  PLN: "Złoty",
  PYG: "Guaraní",
  QAR: "Rial catarí",
  RON: "Leu rumano",
  RSD: "Dinar serbio",
  RUB: "Rublo ruso",
  RWF: "Franco ruandés",
  SAR: "Rial saudí",
  SBD: "Dólar de las Islas Salomón",
  SCR: "Rupia seychelense",
  SDG: "Libra sudanesa",
  SEK: "Corona sueca",
  SGD: "Dólar de Singapur",
  SHP: "Libra de Santa Elena",
  SLL: "Leone",
  SOS: "Chelín somalí",
  SRD: "Dólar surinamés",
  SSP: "Libra sursudanesa",
  STN: "Dobra",
  SVC: "Colón Salvadoreño",
  SYP: "Libra siria",
  SZL: "Lilangeni",
  THB: "Baht",
  TJS: "Somoni tayiko",
  TMT: "Manat turcomano",
  TND: "Dinar tunecino",
  TOP: "Paʻanga",
  TRY: "Lira turca",
  TTD: "Dólar de Trinidad y Tobago",
  TWD: "Nuevo dólar taiwanés",
  TZS: "Chelín tanzano",
  UAH: "Grivna",
  UGX: "Chelín ugandés",
  USD: "Dólar estadounidense",
  UYU: "Peso uruguayo",
  UZS: "Som uzbeko",
  VES2: "Bolívar soberano",
  VND: "Dong vietnamita",
  VUV: "Vatu",
  WST: "Tala",
  XAF: "Franco CFA de África Central",
  XAG: "Plata (denominado en onza troy)",
  XAU: "Oro (denominado en onza troy)",
  XCD: "Dólar del Caribe Oriental",
  XDR: "Derechos especiales de giro",
  XOF: "Franco CFA de África Occidental",
  XPD: "Paladio (denominado en onza troy)",
  XPF: "Franco CFP",
  XPT: "Platino (denominado en onza troy)",
  XSU: "SUCRE",
  YER: "Rial yemení",
  ZAR: "Rand",
  ZMW: "Kwacha zambiano",
  ZWL: "Dólar zimbabuense",
};
