import { KeyValObject } from "./types";

export const AVAIABLE_CURRENCIES: KeyValObject = {
  // AFN: "Afgani",
  // MGA: "Ariary malgache",
  // THB: "Baht",
  // PAB: "Balboa",
  // ETB: "Birr etíope",
  // VES2: "Bolívar soberano",
  BOB: "Boliviano",
  // GHS: "Cedi ghanés",
  // KES: "Chelín keniano",
  // SOS: "Chelín somalí",
  // TZS: "Chelín tanzano",
  // UGX: "Chelín ugandés",
  // CRC: "Colón costarricense",
  // SVC: "Colón Salvadoreño",
  // NIO: "Córdoba",
  CZK: "Corona checa",
  DKK: "Corona danesa",
  ISK: "Corona islandesa",
  NOK: "Corona noruega",
  SEK: "Corona sueca",
  // GMD: "Dalasi",
  // MKD: "Denar",
  // XDR: "Derechos especiales de giro",
  // DZD: "Dinar argelino",
  // BHD: "Dinar bareiní",
  // IQD: "Dinar iraquí",
  // JOD: "Dinar jordano",
  // KWD: "Dinar kuwaití",
  // LYD: "Dinar libio",
  // RSD: "Dinar serbio",
  // TND: "Dinar tunecino",
  // AED: "Dírham de los Emiratos Árabes Unidos",
  // MAD: "Dírham marroquí",
  // STN: "Dobra",
  AUD: "Dólar australiano",
  // BSD: "Dólar bahameño",
  // BBD: "Dólar barbadense",
  // BZD: "Dólar beliceño",
  // BMD: "Dólar bermudeño",
  CAD: "Dólar canadiense",
  // BND: "Dólar de Brunéi",
  // HKD: "Dólar de Hong Kong",
  // KYD: "Dólar de las Islas Caimán",
  // SBD: "Dólar de las Islas Salomón",
  // SGD: "Dólar de Singapur",
  // TTD: "Dólar de Trinidad y Tobago",
  // XCD: "Dólar del Caribe Oriental",
  USD: "Dólar estadounidense",
  // FJD: "Dólar fiyiano",
  // GYD: "Dólar guyanés",
  // JMD: "Dólar jamaiquino",
  // LRD: "Dólar liberiano",
  // NAD: "Dólar namibio",
  NZD: "Dólar neozelandés",
  // SRD: "Dólar surinamés",
  // ZWL: "Dólar zimbabuense",
  // VND: "Dong vietnamita",
  // AMD: "Dram armenio",
  // CVE: "Escudo caboverdiano",
  EUR: "Euro",
  // ANG: "Florín antillano neerlandés",
  // AWG: "Florín arubeño",
  // HUF: "Forinto",
  // XAF: "Franco CFA de África Central",
  // XOF: "Franco CFA de África Occidental",
  // XPF: "Franco CFP",
  // KMF: "Franco comorense",
  // CDF: "Franco congoleño",
  // BIF: "Franco de Burundi",
  // GNF: "Franco guineano",
  // RWF: "Franco ruandés",
  CHF: "Franco suizo",
  // DJF: "Franco yibutiano",
  // HTG: "Gourde",
  // UAH: "Grivna",
  PYG: "Guaraní",
  // PGK: "Kina",
  // LAK: "Kip",
  // HRK: "Kuna",
  // MWK: "Kwacha",
  // ZMW: "Kwacha zambiano",
  // AOA: "Kwanza",
  // MMK: "Kyat",
  // GEL: "Lari",
  // ALL: "Lek",
  // HNL: "Lempira",
  // SLL: "Leone",
  // MDL: "Leu moldavo",
  // RON: "Leu rumano",
  // BGN: "Lev búlgaro",
  // GIP: "Libra de Gibraltar",
  // SHP: "Libra de Santa Elena",
  // EGP: "Libra egipcia",
  GBP: "Libra esterlina",
  // LBP: "Libra libanesa",
  // FKP: "Libra malvinense",
  // SYP: "Libra siria",
  // SDG: "Libra sudanesa",
  // SSP: "Libra sursudanesa",
  // SZL: "Lilangeni",
  TRY: "Lira turca",
  // LSL: "Loti",
  // AZN: "Manat azerbaiyano",
  // TMT: "Manat turcomano",
  // BAM: "Marco convertible",
  // MZN: "Metical mozambiqueño",
  // BOV: "MVDOL",
  // NGN: "Naira",
  // ERN: "Nakfa",
  // BTN: "Ngultrum",
  // TWD: "Nuevo dólar taiwanés",
  ILS: "Nuevo shekel israelí",
  // XAU: "Oro (denominado en onza troy)",
  // TOP: "Paʻanga",
  // XPD: "Paladio (denominado en onza troy)",
  // MOP: "Pataca",
  // ARS: "Peso argentino",
  CLP: "Peso chileno",
  COP: "Peso colombiano",
  // CUC: "Peso convertible",
  CUP: "Peso cubano",
  DOP: "Peso dominicano",
  // PHP: "Peso filipino",
  MXN: "Peso mexicano",
  UYU: "Peso uruguayo",
  // XAG: "Plata (denominado en onza troy)",
  // XPT: "Platino (denominado en onza troy)",
  // BWP: "Pula",
  // GTQ: "Quetzal",
  // ZAR: "Rand",
  BRL: "Real brasileño",
  // QAR: "Rial catarí",
  // IRR: "Rial iraní",
  // OMR: "Rial omaní",
  // SAR: "Rial saudí",
  // YER: "Rial yemení",
  // KHR: "Riel",
  // MYR: "Ringgit malayo",
  // BYN: "Rublo bielorruso",
  RUB: "Rublo ruso",
  // MVR: "Rufiyaa",
  // MUR: "Rupia de Mauricio",
  // LKR: "Rupia de Sri Lanka",
  INR: "Rupia india",
  // IDR: "Rupia indonesia",
  // NPR: "Rupia nepalí",
  // PKR: "Rupia pakistaní",
  // SCR: "Rupia seychelense",
  PEN: "Sol",
  // KGS: "Som",
  // UZS: "Som uzbeko",
  // TJS: "Somoni tayiko",
  // XSU: "SUCRE",
  // BDT: "Taka",
  // WST: "Tala",
  // KZT: "Tenge",
  // MNT: "Tugrik",
  // MRU: "Uguiya",
  // CLF: "Unidad de fomento",
  // MXV: "Unidad de Inversión (UDI) mexicana",
  // VUV: "Vatu",
  KRW: "Won",
  // KPW: "Won norcoreano",
  JPY: "Yen",
  CNY: "Yuan chino",
  // PLN: "Złoty",
};

export const DEFAULT_CURRENCY = "USD";
export const DEFAULT_CURRENCY_LIST_ITEM = { code: "", name: "", value: 0 };